# Generated by Django 5.2 on 2025-12-10 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIAR_USUARIO", "Criação de Usuário"),
                            ("CRIAR_EVENTO", "Criação de Evento"),
                            ("ALTERAR_EVENTO", "Alteração de Evento"),
                            ("EXCLUIR_EVENTO", "Exclusão de Evento"),
                            ("CONSULTA_API_EVENTOS", "Consulta de Eventos via API"),
                            ("INSCRICAO_EVENTO", "Inscrição em Evento"),
                            ("GERAR_CERTIFICADO", "Geração de Certificado"),
                            ("CONSULTAR_CERTIFICADO", "Consulta de Certificado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("dados_adicionais", models.JSONField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "db_table": "log_auditoria",
                "ordering": ["-data_hora"],
            },
        ),
    ]
