# Generated by Django 5.2 on 2025-12-10 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="codigo_confirmacao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="email_confirmado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve estar no formato (XX) XXXXX-XXXX",
                        regex="^\\(\\d{2}\\) \\d{5}-\\d{4}$",
                    )
                ],
            ),
        ),
    ]
