# Generated by Django 5.2 on 2025-12-11 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0002_usuario_codigo_confirmacao_usuario_email_confirmado_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                help_text="Digite apenas números (10 ou 11 dígitos)",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve conter 10 ou 11 dígitos (apenas números)",
                        regex="^\\d{10,11}$",
                    )
                ],
            ),
        ),
    ]
