# Generated by Django 5.2 on 2025-12-10 19:42

import django.core.validators
import django.db.models.deletion
import eventos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=eventos.models.evento_banner_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="professor_responsavel",
            field=models.ForeignKey(
                limit_choices_to={"perfil": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_responsavel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
