# Generated by Django 5.2 on 2025-12-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0003_evento_banner_evento_professor_responsavel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inscricao",
            unique_together=set(),
        ),
    ]
