# Generated by Django 5.2 on 2025-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0004_alter_inscricao_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="presenca_confirmada",
            field=models.BooleanField(
                default=False, help_text="Confirmar presença para liberar certificado"
            ),
        ),
    ]
